config/routes.rb
YunlingOA::Application.routes.draw do

  resources :work_logs

  resources :communicate_messages

  resources :prompt_messages

  resources :application_receivers

  resources :leave_applications

  resources :business_trip_applications

  resources :item_applications

  resources :expense_applications

  resources :payment_applications

  resources :contract_applications

  resources :billing_applications

  resources :notices

  resources :users

  resources :roles
  
  resources :use_car_registrations

  resources :certification_applications

  resource  :session

  match '/signup' => 'users#new', :as => 'signup'
  match '/settings' => 'users#settings', :as => 'settings'
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'

  match 'application/:id/download/' => 'application#download', :as => 'download_application'

  match '/contacts' => 'users#list', :as => 'contacts'

  namespace :admin do
    resources :use_car_registrations
    match 'statistics' => 'certifications#statistics', :as => :statistics
    resources :work_logs
    match 'work_statistics' => 'work_logs#statistics', :as => :work_statistics
  end

  namespace :human_resource do
    resources :leave_applications
    resources :business_trip_applications
  end

  namespace :finance do
    resources :expense_applications
    resources :payment_applications
    resources :contract_applications
    resources :billing_applications
  end

  namespace :sale do
    resources :contract_applications
    resources :billing_applications
  end

  root :to=>'notices#index'

end

app/models/work_log.rb
class WorkLog < ActiveRecord::Base
  
  validates :content, :presence => true
  validates :log_date, :presence => true

  belongs_to :user

  scope :filter_by_month, lambda{|q| where('log_date >= ? and log_date <= ?', q, q.next_month)}

  class << self
    def statistics_by_user(user_name, filter_date)
      users = []
      if user_name.blank?
        users = User.all
      else
        u = User.find_by_real_name(user_name)
        unless u.nil?
          users << u
        end
      end

      result=[]
      users.each do |user|
        record = []
        record << user.real_name
        record << user.work_logs.filter_by_date(filter_date).size
        result << record
      end
      result
    end
  end
end

app/controllers/admin/work_logs_controller.rb
class Admin::WorkLogsController < Admin::BaseController

  def index
    unless params[:q].nil?
      return @work_logs = User.find_by_real_name(params[:real_name]).work_logs.
      filter_by_month(params[:q].to_date).paginate(:page => params[:page]).order('id DESC')
    end
    @work_logs = User.find_by_real_name(params[:real_name]).work_logs.paginate(:page => params[:page]).order('id DESC')
  end

  def statistics
    @statistics = WorkLog.statistics_by_user(params[:user_name], params[:filter_date].nil? ? nil : params[:filter_date].to_date)
  end

end

app/controllers/human_resource/work_logs_controller.rb
class HumanResource::WorkLogsController < HumanResource::BaseController

  def index
    unless params[:q].nil?
      return @work_logs = User.find_by_real_name(params[:real_name]).work_logs.
          filter_by_month(params[:q].to_date).paginate(:page => params[:page]).order('id DESC')
    end
    @work_logs = User.find_by_real_name(params[:real_name]).work_logs.paginate(:page => params[:page]).order('id DESC')
  end

  def statistics
    @statistics = WorkLog.statistics_by_user(params[:user_name], params[:filter_date].nil? ? nil : params[:filter_date].to_date)
  end

end

app/controllers/work_logs_controller.rb
class WorkLogsController < ApplicationController
  before_filter :set_remote_ip, :only => [:create]

  # GET /work_logs
  # GET /work_logs.json
  def index
    if params[:flag] == "subordinate"
      @work_logs = current_user.get_children_work_logs
      .paginate(:page => params[:page]).order('id DESC')
    else
      @work_logs = current_user.work_logs
      .paginate(:page => params[:page]).order('id DESC')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_logs }
    end
  end

  # GET /work_logs/1
  # GET /work_logs/1.json
  def show
    @work_log = WorkLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_log }
    end
  end

  # GET /work_logs/new
  # GET /work_logs/new.json
  def new
    @work_log = WorkLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_log }
    end
  end

  # GET /work_logs/1/edit
  def edit
    @work_log = WorkLog.find(params[:id])
  end

  # POST /work_logs
  # POST /work_logs.json
  def create
    @work_log = WorkLog.new(params[:work_log])
    @work_log.user = current_user

    respond_to do |format|
      if @work_log.save
        format.html { redirect_to @work_log, notice: 'Work log was successfully created.' }
        format.json { render json: @work_log, status: :created, location: @work_log }
      else
        format.html { render action: "new" }
        format.json { render json: @work_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_logs/1
  # PUT /work_logs/1.json
  def update
    @work_log = WorkLog.find(params[:id])

    respond_to do |format|
      if @work_log.update_attributes(params[:work_log])
        format.html { redirect_to @work_log, notice: 'Work log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_logs/1
  # DELETE /work_logs/1.json
  def destroy
    @work_log = WorkLog.find(params[:id])
    @work_log.destroy

    respond_to do |format|
      format.html { redirect_to work_logs_url }
      format.json { head :no_content }
    end
  end

  private
  def set_remote_ip
    return if params[:work_log].nil?
    params[:work_log][:remote_ip] = request.remote_ip
  end
end

app/helpers/work_logs_helper.rb
module WorkLogsHelper
end

app/views/admin/work_logs/index.html.erb
<style>
    .ui-datepicker-calendar {
        display: none;
    }
</style>

<%= render 'side_bar/admin_affaire_side_bar' %>
<h1 style="margin-top:0;"><%= I18n.t("views_work_log.title")%></h1>
<p class="subtitle">
  <%= I18n.t("views_work_log.total_notices_prompt") + ":" + @work_logs.size.to_s %>
</p>
<%= form_tag admin_work_logs_path, :method => 'get' do %>
<p>
  <label><%= I18n.t 'views_work_log.select_find_date', :default => 'select_find_date' %></label>
  <%= text_field_tag :q, params[:q], :class => "monthPicker", :size => '15' %>
  <%= hidden_field_tag :real_name, params[:real_name]%>
<%= submit_tag I18n.t('operate.query') %></p>
<% end %>

<table border="0" cellspacing="0" cellpadding="0" class="wide notices">
  <tr>
    <th class="la" width="25%"><%= I18n.t 'views_work_log.owner' %></th>
    <th class="la" width="25%"><%= I18n.t 'activerecord.attributes.common.create_at' %></th>
    <th class="la" width="25%"><%= I18n.t 'views_work_log.logdate' %></th>
    <th class="la" width="25%"><%= I18n.t 'views_work_log.remote_ip' %></th>
  </tr>

<% @work_logs.each do |work_log| %>
  <tr>
    <td><%= work_log.user_real_name %></td>
    <td><%= l(work_log.created_at, :format => :long) %></td>
    <td><%= work_log.log_date %></td>
    <td><%= work_log.remote_ip %></td>
  </tr>
<% end %>
</table>

<%= render 'application/pagination', :posts => @work_logs %>

app/views/admin/work_logs/show.html.erb
<%= render 'side_bar/admin_affaire_side_bar' %>
<p>
  <b><%= label_tag :content, I18n.t("activerecord.attributes.work_log.cotent")%></b>
  <%= @work_log.content %>
</p>

<%= link_to 'Back', admin_work_statistics_path %>

app/views/admin/work_logs/statistics.html.erb
<style>
.ui-datepicker-calendar {
  display: none;
}
</style>
<%= render 'side_bar/admin_affaire_side_bar' %>
<h1 style="margin-top:0;"><%= I18n.t("views_work_log.work_log_statistics")%></h1>
<p>
<%= form_tag admin_work_statistics_path, :method => 'get' do %>
  <label><%= I18n.t 'views_work_log.select_statistics_date'%></label>
  <%= text_field_tag :filter_date, params[:filter_date], :class => "monthPicker", :size => '15' %>
  <label><%= I18n.t 'views_work_log.select_statistics_user_name'%></label>
  <%= text_field_tag :user_name , params[:user_name], :class=>"autocomplete_input_single_text" %>
  <%= submit_tag I18n.t('operate.query') %>
  <%= button_tag I18n.t('operate.reset'), :class =>"reset" %></p>
<% end %>

<table border="0" cellspacing="0" cellpadding="0" class="wide notices">
  <tr>
    <th class="la" width="33%"><%= I18n.t 'views_work_log.owner' %></th>
    <th class="la" width="33%"><%= I18n.t 'views_work_log.total_num' %></th>
  </tr>

  <% @statistics.each do |statistic| %>
  <tr>
    <td>
      <%= link_to statistic.first, admin_work_logs_path(:real_name => statistic.first), :class => "admin" %>
    </td>
    <!-- <td><%= statistic.first %></td> -->
    <td><%= statistic.last %></td>
  </tr>
  <% end %>
</table>