config/routes.rb
YunlingOA::Application.routes.draw do

  resources :work_logs

  resources :communicate_messages

  resources :prompt_messages

  resources :application_receivers

  resources :leave_applications

  resources :business_trip_applications

  resources :item_applications

  resources :expense_applications

  resources :payment_applications

  resources :contract_applications

  resources :billing_applications

  resources :notices

  resources :users

  resources :roles
  
  resources :use_car_registrations

  resources :certification_applications

  resource  :session

  match '/signup' => 'users#new', :as => 'signup'
  match '/settings' => 'users#settings', :as => 'settings'
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'

  match 'application/:id/download/' => 'application#download', :as => 'download_application'

  match '/contacts' => 'users#list', :as => 'contacts'

  namespace :admin do
    resources :use_car_registrations
    match 'statistics' => 'certifications#statistics', :as => :statistics
    resources :work_logs
    match 'work_statistics' => 'work_logs#statistics', :as => :work_statistics
  end

  namespace :human_resource do
    resources :leave_applications
    resources :business_trip_applications
  end

  namespace :finance do
    resources :expense_applications
    resources :payment_applications
    resources :contract_applications
    resources :billing_applications
  end

  namespace :sale do
    resources :contract_applications
    resources :billing_applications
  end

  root :to=>'notices#index'

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :title, :description
  belongs_to :user
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_filter :find_notice, :only=>[:show, :edit, :update, :destroy]
  # GET /notices
  # GET /notices.xml
  def index
    @notices = Notice.paginate(:page => params[:page]).order('id DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.xml
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @notice }
    end
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.xml
  def create
    @notice = Notice.new(params[:notice])
    @notice.user = current_user
    
    respond_to do |format|
      if @notice.save
        format.html { redirect_to(@notice, :notice => 'Notice was successfully created.') }
        format.xml  { render :xml => @notice, :status => :created, :location => @notice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @notice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.xml
  def update
    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to(@notice, :notice => 'Notice was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @notice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.xml
  def destroy
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to(notices_url) }
      format.xml  { head :ok }
    end
  end

  private
    def find_notice
      @notice = Notice.find(params[:id])
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(notice) do |f| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit I18n.t("submit.location.#{params[:action]}")%>
  </div>
<% end %>

app/views/notices/edit.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h1>Editing notice</h1>

<%= render 'form', :notice=>@notice%>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h1 style="margin-top:0;"><%= I18n.t("views_notice.title")%></h1>

<table border="0" cellspacing="0" cellpadding="0" class="wide notices">
  <tr>
    <th class="la" width="70%" colspan="2"><%= I18n.t 'activerecord.models.notice', :default => 'notice' %></th>
    <th class="la" width="30%" colspan="1"><%= I18n.t('activerecord.attributes.notice.created_at', :default => 'publish time') %></th>
  </tr>
  <% for notice in @notices do %>
  <tr class="notice" id="notice_<%= notice.id %>_row">
    <td class="c2 vat" width="50%">
      <%= link_to notice.title, notice_path(notice), :class => "title" %>
      <p class="desc"><%= truncate(strip_tags(notice.description),
                 :length => 60)%></p>
    </td>
    <td class="c3" width="20%">
      <%= link_to  I18n.t('operate.edit'), edit_notice_path(notice), :class => "tiny", :rel => "directory", :style => "float:right" %><br/>
      <%= link_to  I18n.t('operate.delete'), notice, :class => "tiny", :rel => "directory", :style => "float:right", :confirm => 'Are you sure?', :method => :delete %>
    </td>

    <td class="inv lp">
      <%= I18n.t 'views_notice.publish_time_details', :when => notice.created_at%><br />
      <strong><%= I18n.t 'views_notice.publisher_details', :user => notice.user_real_name %></strong>
    </td>
  </tr>
<% end %>
</table>

<%= render 'application/pagination', :posts =>  @notices %>

<p><%= link_to I18n.t('operate.new') + I18n.t('activerecord.models.notice'), new_notice_path, :class => "utility" %></p>

app/views/notices/new.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h1><%= I18n.t("operate.new") + I18n.t("activerecord.models.notice")%></h1>

<%= render 'form' ,:notice=>@notice%>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<p>
  <b><%= @notice.title %></b>
</p>

<p>
  <%= @notice.description %>
</p>

<%= link_to I18n.t('operate.edit'), edit_notice_path(@notice) %> |
<%= link_to I18n.t('operate.back'), notices_path %>