config/routes.rb
YunlingOA::Application.routes.draw do

  resources :work_logs

  resources :communicate_messages

  resources :prompt_messages

  resources :application_receivers

  resources :leave_applications

  resources :business_trip_applications

  resources :item_applications

  resources :expense_applications

  resources :payment_applications

  resources :contract_applications

  resources :billing_applications

  resources :notices

  resources :users

  resources :roles
  
  resources :use_car_registrations

  resources :certification_applications

  resource  :session

  match '/signup' => 'users#new', :as => 'signup'
  match '/settings' => 'users#settings', :as => 'settings'
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'

  match 'application/:id/download/' => 'application#download', :as => 'download_application'

  match '/contacts' => 'users#list', :as => 'contacts'

  namespace :admin do
    resources :use_car_registrations
    match 'statistics' => 'certifications#statistics', :as => :statistics
    resources :work_logs
    match 'work_statistics' => 'work_logs#statistics', :as => :work_statistics
  end

  namespace :human_resource do
    resources :leave_applications
    resources :business_trip_applications
  end

  namespace :finance do
    resources :expense_applications
    resources :payment_applications
    resources :contract_applications
    resources :billing_applications
  end

  namespace :sale do
    resources :contract_applications
    resources :billing_applications
  end

  root :to=>'notices#index'

end

app/models/billing_application.rb
class BillingApplication < Application
  validates :reason, :presence => true
  validates :purchase_company, :presence => true
  validates :sum, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :use, :presence => true

  USE = [
    I18n.t("init_data.billing_application.use.invoice_17percent"),
    I18n.t("init_data.billing_application.use.invoice_6percent"),
    I18n.t("init_data.application.use.other")
  ]

  scope :pending_finance_opinion, lambda{where("finance_opinion is null and state= 'approved'")}
end

app/controllers/billing_applications_controller.rb
class BillingApplicationsController < ApplicationController

  def index
    @size = current_user.send_applications.billing_applications.size
    @billing_applications = current_user.send_applications.billing_applications
      .paginate(:page => params[:page]).order('id DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @billing_applications }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @billing_application = BillingApplication.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @billing_application }
    end
  end


  def create
    @billing_application = BillingApplication.new(params[:billing_application])
    @billing_application.sender = current_user

    respond_to do |format|
      if @billing_application.save
        format.html { redirect_to(@billing_application, :notice => 'billing_applications was successfully created.') }
        format.xml  { render :xml => @billing_application, :status => :created, :location => @billing_application }
      else
        format.html { render "new" }
        format.xml  { render :xml => @billing_application.errors, :status => :unprocessable_entity }
      end
    end

  end

  def show
    @billing_application = BillingApplication.find(params[:id])
    # BillingApplication.find_by_message_and_receiver(@communicate_message, current_user).first.read_message!
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @billing_application }
    end
  end

  def destroy
    @billing_application = BillingApplication.find(params[:id])
    @billing_application.destroy

    respond_to do |format|
      format.html { redirect_to(billing_applications_url, :notice=>"billing_application was successfully deleted.") }
      format.xml  { head :ok }
    end
  end
end

app/controllers/finance/billing_applications_controller.rb
class Finance::BillingApplicationsController < Finance::BaseController
  def index
    @billing_applications = BillingApplication.where("state='approved'").paginate(:page => params[:page]).order('id DESC')
  end

  def show
  	@billing_application = BillingApplication.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @billing_application }
    end
  end

  def edit
    @billing_application = BillingApplication.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.xml  { render :xml => @billing_application }
    end
  end

  def update
    @billing_application = BillingApplication.find(params[:id])

    respond_to do |format|
      if @billing_application.update_attributes(params[:billing_application])
        format.html { redirect_to(finance_billing_applications_path, :notice => 'billing_application was successfully update.') }
      else
        format.html { render "edit" }
      end
    end
  end

end

app/controllers/sale/billing_applications_controller.rb
class Sale::BillingApplicationsController < Sale::BaseController
  def index
    @billing_applications = BillingApplication.where("state='approved'").paginate(:page => params[:page]).order('id DESC')
  end

  def show
  	@billing_application = BillingApplication.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @billing_application }
    end
  end
end

app/views/billing_applications/_detail_info.html.erb
<div>
<table border="1" width="100%">
  <tr>
    <td width="20%" class="la">
      <label>
        <%= I18n.t 'activerecord.attributes.billing_application.purchase_company' %>
      </label>
    </td>
    <td width="80%" class="la"><%= application.purchase_company %></td>
  </tr>

  <tr>
    <td>
      <label>
        <%= I18n.t 'activerecord.attributes.billing_application.use' %>
      </label>
    </td>
    <td><%= application.use %></td>
  </tr>

  <tr>
    <td>
      <label>
        <%= I18n.t 'activerecord.attributes.billing_application.sum' %>
      </label>
    </td>
    <td><%= application.sum %></td>
  </tr>

  <tr>
    <td>
      <label>
        <%= I18n.t 'activerecord.attributes.billing_application.reason' %>
      </label>
    </td>
    <td><%= application.reason %></td>
  </tr>
  <%if application.attachment_file.exists? %>
      <tr>
        <td>
          <label>
            <%= I18n.t 'activerecord.attributes.application.attachment_file' %>
          </label>
        </td>
        <td><%= link_to(application.attachment_file_file_name, download_application_path(application)) %></td>
      </tr>
  <%end%>

  <%= render("application/detail_state_info", :application => application) %>
</table>
</div>

app/views/billing_applications/index.html.erb
<%= render 'side_bar/daily_office_side_bar' %>

<h1 style="margin-top:0;">
  <%= I18n.t "activerecord.models.billing_application" %>
</h1>
<p class="subtitle">
  <%= I18n.t "views_billing_application.total_application_prompt" %>:&nbsp;
  <%= @size %>
</p>

<table border="0" cellspacing="0" cellpadding="0" class="wide notices">
  <tr>
    <th width="55%" class="la">
      <%= I18n.t 'activerecord.attributes.billing_application.purchase_company' %>
    </th>
    <th width="15%" class="la">
      <%= I18n.t 'activerecord.attributes.common.state' %>
    </th>
    <th width="30%" class ="la">
      <%= I18n.t 'activerecord.attributes.application.created_at' %>
    </th>
  </tr>
  <% @billing_applications.each do |application| %>
    <tr>
      <td>
        <%= link_to application.purchase_company, application, :class => "admin" %>
        <%= link_to  I18n.t('operate.delete'), application, :class => "tiny", :rel => "directory", :style => "float:right", :confirm => 'Are you sure?', :method => :delete %>
      </td>
      <td>
        <%= application.state_I18n %>
      </td>
      <td><%= application.created_at %></td>
    </tr>
  <% end %>
</table>

<%= render 'application/pagination', :posts =>  @billing_applications %>

<p>
  <%= link_to I18n.t('operate.new') + I18n.t("activerecord.models.billing_application"), new_billing_application_path, :class => "utility" %>
</p>

app/views/billing_applications/new.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<%= form_for @billing_application do |f| %>
  <% if @billing_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billing_application.errors.count, "error") %>
        &nbsp;prohibited this user from being saved:</h2>
      <ul>
        <% @billing_application.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <h3><%= I18n.t 'views_billing_application.title' %></h3>
  </p>

  <p>
    <label for="item_name">
      <%= I18n.t 'activerecord.attributes.billing_application.purchase_company'%>
    </label><br/>
    <%= f.text_field :purchase_company, :size => "60" %>
  </p>

  <p>
    <label for="use">
    	<%= I18n.t 'activerecord.attributes.billing_application.use'%>
    </label>
    <br />
    <%= render 'application/use_radio', :f => f, :use_names => BillingApplication::USE%>
  </p>

  <p>
    <label for="sum">
    	<%= I18n.t 'activerecord.attributes.billing_application.sum'%>
    </label><br/>
    <%= f.text_field :sum, :size => "5" %>
  </p>

  <p>
    <label for="reason"><%= I18n.t 'activerecord.attributes.billing_application.reason'%>
    </label><br/>
    <%= f.text_area :reason, :size => "60x3" %>
  </p>

  <p>
    <label for="reason"><%= I18n.t 'activerecord.attributes.application.attachment_file'%></label><br/>
    <%= f.file_field :attachment_file %>
  </p>

  <p><%= submit_tag I18n.t('operate.commit') %></p>
<% end %>

<%= link_to I18n.t('operate.back'), billing_applications_path %>

app/views/billing_applications/show.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h3><%= I18n.t 'views_billing_application.title' %></h3>

<%= render 'detail_info', :application=>@billing_application %>

<%= link_to I18n.t('operate.back'), billing_applications_path %>