config/routes.rb
YunlingOA::Application.routes.draw do

  resources :work_logs

  resources :communicate_messages

  resources :prompt_messages

  resources :application_receivers

  resources :leave_applications

  resources :business_trip_applications

  resources :item_applications

  resources :expense_applications

  resources :payment_applications

  resources :contract_applications

  resources :billing_applications

  resources :notices

  resources :users

  resources :roles
  
  resources :use_car_registrations

  resources :certification_applications

  resource  :session

  match '/signup' => 'users#new', :as => 'signup'
  match '/settings' => 'users#settings', :as => 'settings'
  match '/login' => 'sessions#new', :as => 'login'
  match '/logout' => 'sessions#destroy', :as => 'logout'

  match 'application/:id/download/' => 'application#download', :as => 'download_application'

  match '/contacts' => 'users#list', :as => 'contacts'

  namespace :admin do
    resources :use_car_registrations
    match 'statistics' => 'certifications#statistics', :as => :statistics
    resources :work_logs
    match 'work_statistics' => 'work_logs#statistics', :as => :work_statistics
  end

  namespace :human_resource do
    resources :leave_applications
    resources :business_trip_applications
  end

  namespace :finance do
    resources :expense_applications
    resources :payment_applications
    resources :contract_applications
    resources :billing_applications
  end

  namespace :sale do
    resources :contract_applications
    resources :billing_applications
  end

  root :to=>'notices#index'

end

app/models/use_car_registration.rb
class UseCarRegistration < ActiveRecord::Base
  attr_accessible :end_at_date, :end_km_num, :real_user_name, :reason, :start_at_date, :start_km_num
  belongs_to :user
end

app/controllers/admin/use_car_registrations_controller.rb
class Admin::UseCarRegistrationsController < Admin::BaseController
  def index
    @use_car_registrations = UseCarRegistration.paginate(:page => params[:page]).order('id DESC')
  end

  def show
  	@use_car_registration = UseCarRegistration.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

end

app/controllers/use_car_registrations_controller.rb
class UseCarRegistrationsController < ApplicationController

  def index
    @use_car_registrations = current_user.use_car_registrations.paginate(:page => params[:page]).order('id DESC')
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @use_car_registration = UseCarRegistration.new
    respond_to do |format|
      format.html # new.html.erb
    end
  end


  def create
    @use_car_registration = UseCarRegistration.new(params[:use_car_registration])
    @use_car_registration.user = current_user

    respond_to do |format|
      if @use_car_registration.save
        format.html { redirect_to(@use_car_registration, :notice => 'use_car_registration was successfully created.') }
      else
        format.html { render "new" }
      end
    end

  end

  def show
    @use_car_registration = UseCarRegistration.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def edit
    @use_car_registration = UseCarRegistration.find(params[:id])
  end

  def update
    @use_car_registration = UseCarRegistration.find(params[:id])
    respond_to do |format|
      if @use_car_registration.update_attributes(params[:use_car_registration])
        format.html { redirect_to(@use_car_registration, :notice => 'use_car_registration was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

end

app/helpers/use_car_registration_helper.rb
module UseCarRegistrationHelper
end

app/views/use_car_registrations/_detail_info.html.erb
<div>
<table border="1" width="100%">
  <tr>
    <td>
      <label>
        <%= I18n.t 'views_use_car_registration.real_user_name' %>
      </label>
    </td>
    <td colspan="3">
      <%= use_car_registration.real_user_name %>
    </td>
  </tr>
  <tr>
    <td width="20%" class="la">
      <label>
        <%= I18n.t 'views_use_car_registration.start_at_date' %>
      </label>
    </td>
    <td width="30%" class="la">
      <%= use_car_registration.start_at_date %>
    </td>
    <td width="20%" class="la">
      <label>
        <%= I18n.t 'views_use_car_registration.end_at_date' %>
      </label>
    </td>
    <td width="30%" class="la">
      <%= use_car_registration.end_at_date %>
    </td>
  </tr>

  <tr>
    <td width="20%" class="la">
      <label>
        <%= I18n.t 'views_use_car_registration.start_km_num' %>
      </label>
    </td>
    <td width="30%" class="la">
      <%= use_car_registration.start_km_num %>
    </td>
    <td width="20%" class="la">
      <label>
        <%= I18n.t 'views_use_car_registration.end_km_num' %>
      </label>
    </td>
    <td width="30%" class="la">
      <%= use_car_registration.end_km_num %>
    </td>
  </tr>

  <tr>
    <td>
      <label>
        <%= I18n.t 'views_use_car_registration.reason' %>
      </label>
    </td>
    <td colspan="3">
      <%= use_car_registration.reason %>
    </td>
  </tr>
</table>
</div>

app/views/use_car_registrations/_form.html.erb
<%= form_for(use_car_registration) do |f| %>
  <% if use_car_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(use_car_registration.errors.count, "error") %> prohibited this use_car_registration from being saved:</h2>

      <ul>
      <% use_car_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div><h3><%= I18n.t 'views_use_car_registration.title' %></h3></div>

  <div><p>
    <label for="real_user_name" >
      <%= I18n.t 'views_use_car_registration.real_user_name' %>
    </label>
    <%= f.text_field :real_user_name, :size => '15' %>
  </p></div>

  <div><p>
    <label for="start_at_date" >
      <%= I18n.t 'views_use_car_registration.start_at_date' %>
    </label>
    <%= f.text_field :start_at_date, :class => "datePicker", :size => '15' %>
  </p></div>

  <div><p>
    <label for="end_at_date" >
      <%= I18n.t 'views_use_car_registration.end_at_date' %>
    </label>
    <%= f.text_field :end_at_date, :class => "datePicker", :size => '15' %>
  </p></div>


  <div><p>
    <label for="start_km_num" >
      <%= I18n.t 'views_use_car_registration.start_km_num' %>
    </label>
    <%= f.text_field :start_km_num, :size => '15' %>
  </p></div>

  <div><p>
    <label for="end_km_num" >
      <%= I18n.t 'views_use_car_registration.end_km_num' %>
    </label>
    <%= f.text_field :end_km_num, :size => '15' %>
  </p></div>

  <div><p>
    <label for="reason"><%= I18n.t 'views_use_car_registration.reason'%>
    </label><br/>
    <%= f.text_area :reason, :size => "60x3" %>
  </p></div>

  <div><p><%= submit_tag I18n.t('operate.commit') %></p></div>
<% end %>

app/views/use_car_registrations/edit.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h1>Editing notice</h1>

<%= render 'form', :use_car_registration=>@use_car_registration%>

<%= link_to I18n.t('operate.show'), @use_car_registration %> |
<%= link_to I18n.t('operate.back'), use_car_registrations_path %>

app/views/use_car_registrations/index.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h1 style="margin-top:0;"><%= I18n.t("views_use_car_registration.title")%></h1>

<table border="0" cellspacing="0" cellpadding="0" class="wide notices">
  <tr>
    <th class="la" width="20%"><%= I18n.t 'views_use_car_registration.real_user_name'%></th>
    <th class="la" width="20%"><%= I18n.t('views_use_car_registration.start_at_date') %></th>
    <th class="la" width="20%"><%= I18n.t('views_use_car_registration.end_at_date') %></th>
    <th class="la" width="20%"><%= I18n.t('views_use_car_registration.start_km_num') %></th>
    <th class="la" width="20%"><%= I18n.t('views_use_car_registration.end_km_num') %></th>
  </tr>

  <% @use_car_registrations.each do |use_car_registration| %>
    <tr>
      <td>
        <%= link_to use_car_registration.real_user_name, use_car_registration_path(use_car_registration), :class => "admin" %>
      </td>

      <td><%= use_car_registration.start_at_date %></td>
      <td><%= use_car_registration.end_at_date %></td>
      <td><%= use_car_registration.start_km_num%></td>
      <td><%= use_car_registration.end_km_num%></td>
    </tr>
  <% end %>
</table>
</table>

<%= render 'application/pagination', :posts =>  @use_car_registrations %>

<p><%= link_to I18n.t('operate.new') + I18n.t('activerecord.models.use_car_registration'), new_use_car_registration_path, :class => "utility" %></p>

app/views/use_car_registrations/new.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h1><%= I18n.t("operate.new") + I18n.t("activerecord.models.use_car_registration")%></h1>

<%= render 'form' ,:use_car_registration=>@use_car_registration%>

<%= link_to I18n.t('operate.back'), use_car_registrations_path %>

app/views/use_car_registrations/show.html.erb
<%= render 'side_bar/daily_office_side_bar' %>
<h3><%= I18n.t 'operate.details' %></h3>

<%= render("detail_info", :use_car_registration => @use_car_registration) %>

<%= link_to I18n.t('operate.edit'), edit_use_car_registration_path(@use_car_registration) %>
<%= link_to I18n.t('operate.back'), use_car_registrations_path %>